# Generated by Django 4.2.4 on 2023-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('TN', 'Tанк'), ('HL', 'Хил'), ('DD', 'Дамагер'), ('TR', 'Торговец'), ('GM', 'Гилдмастер'), ('QG', 'Квестгивер'), ('BS', 'Кузнец'), ('TN', 'Кожевник'), ('PM', 'Зельевар'), ('SM', 'Мастер заклинаний')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
